### ISSUE TITLE
Setup difficulty

### ISSUE THREAD

**Issue by geoffwalmsley** [MultiChain/multichain-explorer#1]
I'm trying to setup explorer for a multichain running on digitalocean ubuntu 14.04. Have followed installation and setup according to README-MULTICHAIN.txt, but am having difficulty understanding step 4: configure the explorer. 

Where should I place the MCE config file? What should it be named? in params.dat I don't see anything that resembles: magic handshake, address and script address bytes, so I'm not sure what to copy.

IS it possible to get more detailed guidance on how to carry out these steps?

MAny thanks

**Comment by bitcartel** [comment]
README and example config files have been updated.

The config file can be named anything and located anywhere, but for now it's best to just have in the same folder as the repository.

There's no need to copy magic values from params.dat anymore, the explorer now reads them from params.dat file when setting up the database for the chain.
