### ISSUE TITLE
Address does not exist

### ISSUE THREAD

**Issue by MitchK** [MultiChain/multichain-explorer#10]
Hi,

I have a question. Not sure if it actually is a bug, if not, I would like to understand why this happens.

If I click on the miner address of the first two blocks (block 0 and block 1), it shows me 

"Sorry, /address/1UcyC7TeBz4Dk... does not exist on this server."

If I click on the exact same address on the third block (block 2), it actually shows me the address information. Why is this?

**Comment by bitcartel** [comment]
What are the actual links being used for the first three blocks?  Are they exactly the same or do they point to different pages, with perhaps a subtle difference, say a character at the end?  What happens if you shut down the explorer, clear your browser cache, and restart the explorer?

**Comment by bitcartel** [comment]
Closing this ticket as almost a year old.
