### ISSUE TITLE
JsonrpcException: getrawtransaction: No information available about transaction (code -710)

### ISSUE THREAD

**Issue by darthf1** [MultiChain/multichain-explorer#22]
Hi, I got the explorer working on another PC so im unsure as to why its not working right now. I got a PC with Ubuntu Server 16.04.2 and want to start the explorer, however the following error is preventing me from that:

>Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 1, 'chain_id': 1, 'loader': u'default', 'conf': None, 'dirname': u'/home/USER/.multichain/development', 'id': 10}
> Traceback (most recent call last):
>   File "Mce/DataStore.py", line 2892, in catch_up
>     if not store.catch_up_rpc(dircfg):
>   File "Mce/DataStore.py", line 3117, in catch_up_rpc
>     tx = get_tx(rpc_tx_hash)
>   File "Mce/DataStore.py", line 2974, in get_tx
>     rpc_tx_hex = rpc("getrawtransaction", rpc_tx_hash)
>   File "Mce/DataStore.py", line 2949, in rpc
>     ret = util.jsonrpc(chain_name, url, func, *params)
>   File "Mce/util.py", line 246, in jsonrpc
>     raise JsonrpcException(resp['error'], method, params)
> JsonrpcException: getrawtransaction: No information available about transaction (code -710)
>

I've setup a multichain with protocol 10006 because that was the same protocol I was running on another PC. on the other multichain protocols i got the same error.

**Comment by gidgreen** [comment]
There's a general issue with the MultiChain Explorer and the protocol version used by default in the latest MultiChain alpha 29 release. We're looking into this now.

**Comment by gidgreen** [comment]
This should now be fixed in the latest version of the Explorer - if so please close the issue.

**Comment by bitcartel** [comment]
@darthf1 Was this issue resolved?  Thanks.

**Comment by darthf1** [comment]
Apologies, late reply. Since this issue is 2 years old I'll close it, don't have a setup to test anymore.
