### ISSUE TITLE
RPC failed: No JSON object could be decoded

### ISSUE THREAD

**Issue by amithanamakkanavar** [MultiChain/multichain-explorer#23]
I followed the steps given for running Explorer, but this isn't  working. getting RPC failed: No JSON object could be decoded error

**Comment by gidgreen** [comment]
What version of MultiChain are you using?

**Comment by amithanamakkanavar** [comment]
multichain-1.0-beta-1

**Comment by amithanamakkanavar** [comment]
MultiChain utilities build 1.0 alpha 29

**Comment by gidgreen** [comment]
See: http://www.multichain.com/qa/4873/rpc-failed-no-json-object-could-be-decoded

**Comment by amithanamakkanavar** [comment]
That question is raised by me.

**Comment by amithanamakkanavar** [comment]
How can you close the request without solving it?

**Comment by gidgreen** [comment]
Because the discussion has moved to the MultiChain Q&A.
