### ISSUE TITLE
Multichain 2.0 Support

### ISSUE THREAD

**Issue by SDVII** [MultiChain/multichain-explorer#44]
Hello,
I am wondering if or/and when will Multichain 2.0 be supported by the explorer.
Thanks in advance.

**Comment by gidgreen** [comment]
Yes, it will be. Most of it is already built internally, once MC 2.0 enters beta we will release the Explorer as well.

**Comment by gidgreen** [comment]
Yes, it will be. Most of it is already built internally, once MC 2.0 enters beta we will release the Explorer as well.

**Comment by SDVII** [comment]
Thank you for the reply.
If it's not too much to ask, when would MC 2.0 enter beta (even an estimate would suffice).

**Comment by gidgreen** [comment]
MC 2.0 alpha 6 was released today, and this is feature complete. So we expect beta before the end of 2018.

**Comment by SDVII** [comment]
Thank you for your response. Looking forward to the release. Keep up the good work!

**Comment by inayat82** [comment]
HI why Dont you Guys Open Small Website And Sell This Product Or Provide Support For Some Small $$$.?
Like WE have to Wait so long for Get things Done ...

**Comment by SDVII** [comment]
They do offer such support : https://www.multichain.com/pricing/,

Please don't forget that this code is open source and that they really don't have any obligation towards updating these tools. Let's not be ungrateful

**Comment by inayat82** [comment]
Ow Look At the Price.
