### ISSUE TITLE
postgres support

### ISSUE THREAD

**Issue by CzechJiri** [MultiChain/multichain-explorer#9]
While MCE is based on ABE, it looks like postgres support was carved out and removed. 

Any reason why and if this can be put back?

**Comment by gidgreen** [comment]
We're not devoting resources to supporting other databases at the moment, because SQLite works well enough for the web-based explorer. We might revisit this decision in future.

**Comment by reiven** [comment]
@gidgreen same thing with MySQL?

**Comment by gidgreen** [comment]
Yes, at the moment we're supporting SQLite only.
